const SECURITY_INCIDENT_ACTIONS = ["acknowledge_awareness", "classify", "correct_assessment", "decide_authority", "prepare_authority_export", "record_authority_submission", "decide_subject", "prepare_subject_notification", "send_subject_notification", "resolve_subject_notification_unknown", "reconcile_subject_notifications", "set_legal_hold", "release_legal_hold", "close"] as const;
const incidentRevision = { type: "integer", minimum: 0 };
const incidentText = (max: number) => ({ type: "string", minLength: 1, maxLength: max });
const assessmentProperties = { details: incidentText(50_000), detectedAt: { type: "string", format: "date-time" }, occurredAt: { type: "string", format: "date-time" }, containedAt: { type: "string", format: "date-time" }, categories: incidentText(4_000), dataSubjectCount: incidentText(256), recordCount: incidentText(256), specialData: { type: "boolean" }, confidentialityImpact: incidentText(2_000), integrityImpact: incidentText(2_000), availabilityImpact: incidentText(2_000), consequences: incidentText(8_000), likelihood: incidentText(1_000), severity: incidentText(1_000), containment: incidentText(8_000), remediation: incidentText(8_000), prevention: incidentText(8_000), postmortem: incidentText(8_000) };
const incidentAction = (action: string, required: readonly string[], properties: Record<string, unknown>) => ({ type: "object", additionalProperties: false, required: ["action", "expectedRevision", ...required], properties: { action: { const: action }, expectedRevision: incidentRevision, ...properties } });
const SECURITY_INCIDENT_ACTION_SCHEMAS = [
  incidentAction("acknowledge_awareness", [], {}),
  incidentAction("classify", ["classification", "reason"], { classification: { type: "string", enum: ["triage", "breach_confirmed", "not_a_breach"] }, reason: incidentText(4_000) }),
  incidentAction("correct_assessment", ["reason", ...Object.keys(assessmentProperties).filter((key) => key !== "occurredAt" && key !== "containedAt")], { reason: incidentText(4_000), ...assessmentProperties }),
  incidentAction("decide_authority", ["decision", "reason"], { decision: { type: "string", enum: ["required", "not_required"] }, reason: incidentText(4_000), legalException: { type: "string", maxLength: 4_000 } }),
  incidentAction("prepare_authority_export", ["payload"], { payload: incidentText(100_000) }),
  incidentAction("record_authority_submission", ["channel", "reference", "evidence"], { channel: incidentText(128), reference: incidentText(512), evidence: incidentText(20_000), supplementary: { type: "boolean", default: false }, delayReason: { type: "string", minLength: 1, maxLength: 4_000 } }),
  incidentAction("decide_subject", ["decision", "reason"], { decision: { type: "string", enum: ["required", "not_required"] }, reason: incidentText(4_000), legalException: { type: "string", maxLength: 4_000 } }),
  incidentAction("prepare_subject_notification", ["recipients", "subject", "text"], { recipients: { type: "array", minItems: 1, maxItems: 500, items: { type: "string", format: "email", maxLength: 320 } }, subject: incidentText(300), text: incidentText(50_000) }),
  incidentAction("send_subject_notification", ["recipientPseudonym", "snapshotVersion"], { recipientPseudonym: { type: "string", pattern: "^[A-Za-z0-9_-]{16,128}$" }, snapshotVersion: { type: "integer", minimum: 1 } }),
  incidentAction("resolve_subject_notification_unknown", ["deliveryId", "outcome", "reason"], { deliveryId: { type: "string", format: "uuid" }, outcome: { type: "string", enum: ["sent", "failed"] }, reason: incidentText(4_000) }),
  incidentAction("reconcile_subject_notifications", [], {}), incidentAction("set_legal_hold", ["reason"], { reason: incidentText(4_000) }), incidentAction("release_legal_hold", ["reason"], { reason: incidentText(4_000) }), incidentAction("close", [], {}),
] as const;

export const OPENAPI_DOCUMENT = Object.freeze({
  openapi: "3.1.0",
  info: { title: "Patternly Backend API", version: "1.0.0" },
  servers: [{ url: "/" }],
  security: [{ bearerAuth: [] }],
  paths: {
    "/health": { get: { security: [], responses: { "200": { description: "Process is alive" } } } },
    "/ready": { get: { security: [], responses: { "200": { description: "Dependencies are ready" }, "503": { description: "Dependency unavailable" } } } },
    "/openapi.json": { get: { security: [], responses: { "200": { description: "OpenAPI document" } } } },
    "/v1/webhooks/revenuecat": { post: { security: [], description: "Receive one authenticated, idempotent RevenueCat lifecycle event, bind an initial purchase to the active attempt, deliver its durable receipt, and update the canonical Premium projection.", parameters: [{ name: "Authorization", in: "header", required: true, schema: { type: "string", minLength: 1 } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["event"], properties: { event: { type: "object", additionalProperties: true } } } } } }, responses: { "200": { description: "Event processed, ignored, or replayed" }, "400": { description: "Malformed event" }, "401": { description: "Webhook authorization failed" }, "503": { description: "Webhook or durable receipt delivery is unavailable; sender should retry" } } } },
    "/v1/me": { get: { responses: { "200": { description: "Canonical account identity" }, "401": { description: "Authentication required" } } } },
    "/v1/legal-acceptances": { post: { description: "Record an immutable, versioned Terms and minimum-age acceptance for the authenticated account.", responses: { "201": { description: "Acceptance recorded" }, "400": { description: "Invalid acceptance" }, "401": { description: "Authentication required" } } } },
    "/v1/purchase-confirmations": { post: { description: "Record the immutable pre-contract offer and express immediate-start request before opening App Store checkout.", responses: { "201": { description: "Confirmation recorded" }, "400": { description: "Invalid confirmation" }, "401": { description: "Authentication required" } } } },
    "/v1/entitlements": { get: { responses: { "200": { description: "Account entitlement projection" } } } },
    "/v1/progress": { get: { responses: { "200": { description: "Canonical progress state and account revision" } } } },
    "/v1/account-data/export": { get: { description: "Download a bounded JSON account-data export after recent reauthentication. The response is an attachment and is never persisted as a payload.", responses: { "200": { description: "JSON account-data attachment", headers: { "Cache-Control": { schema: { type: "string", const: "private, no-store" } }, "Content-Disposition": { schema: { type: "string" } } }, content: { "application/json": { schema: { "$ref": "#/components/schemas/AccountDataExport" } } } }, "401": { description: "Authentication or recent reauthentication required", headers: { "Cache-Control": { schema: { type: "string", const: "private, no-store" } } } }, "413": { description: "Serialized export exceeds the configured maximum" }, "429": { description: "Per-account export rate limit exceeded", headers: { "Retry-After": { schema: { type: "integer", minimum: 1 } } } } } } },
    "/v1/privacy-requests": { post: { description: "Create one authenticated privacy-right case", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/CreateAccountPrivacyRequest" } } } }, responses: { "201": { description: "Privacy request created" }, "401": { description: "Authentication or recent reauthentication required" } } }, get: { description: "List minimal metadata for the authenticated subject's own privacy requests", responses: { "200": { description: "Privacy request list" } } } },
    "/v1/privacy-requests/{requestId}": { get: { description: "Read one own privacy response after recent reauthentication", parameters: [{ "$ref": "#/components/parameters/PrivacyRequestId" }], responses: { "200": { description: "Privacy response" }, "401": { description: "Recent reauthentication required" }, "404": { description: "Request unavailable" } } } },
    "/v1/public/privacy-requests": { post: { security: [], description: "Accept a non-enumerating guest privacy request and send an email-possession link", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/CreatePublicPrivacyRequest" } } } }, responses: { "202": { description: "Request accepted without disclosing matching data" }, "429": { description: "Rate limited" }, "503": { description: "Email delivery unavailable" } } } },
    "/v1/public/privacy-requests/{requestId}/session": { post: { security: [], description: "Exchange a one-time fragment token for a short object-scoped session", parameters: [{ "$ref": "#/components/parameters/PrivacyRequestId" }], requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/PrivacyTokenExchange" } } } }, responses: { "200": { description: "Short privacy-request session" }, "404": { description: "Uniform unavailable response" } } } },
    "/v1/public/privacy-requests/{requestId}/response": { post: { security: [], description: "Read guest request status and an unexpired response with an object-scoped session", parameters: [{ "$ref": "#/components/parameters/PrivacyRequestId" }], requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/PublicPrivacySession" } } } }, responses: { "200": { description: "Privacy response" }, "404": { description: "Uniform unavailable response" } } } },
    "/v1/legal-requests": { post: { description: "Create an authenticated consumer complaint, withdrawal, non-personal data recovery request, or suspension appeal and email a durable receipt.", responses: { "201": { description: "Consumer case received" }, "401": { description: "Authentication required" }, "503": { description: "Email delivery unavailable" } } }, get: { description: "List the authenticated account's consumer cases.", responses: { "200": { description: "Consumer case list" } } } },
    "/v1/legal-requests/{requestId}": { get: { description: "Read one consumer case owned by the authenticated account.", responses: { "200": { description: "Consumer case" }, "404": { description: "Case unavailable" } } } },
    "/v1/public/legal-requests": { post: { security: [{ appCheckAuth: [] }], description: "Create a guest consumer case with App Check, bounded rate limiting, and a durable email receipt.", parameters: [{ "$ref": "#/components/parameters/FirebaseAppCheck" }], responses: { "201": { description: "Consumer case received" }, "401": { description: "Valid App Check required" }, "429": { description: "Rate limited" }, "503": { description: "Email delivery unavailable" } } } },
    "/v1/progress/sync": { post: { requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/SyncRequest" } } } }, responses: { "200": { description: "Applied or duplicate mutations" }, "409": { description: "Progress or account revision conflict" } } } },
    "/v1/account-data/adoption/preview": { post: { description: "Preview local account-data adoption without binding or writing learning records", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/GuestMergeSnapshot" } } } }, responses: { "200": { description: "Deterministic adoption preview" }, "400": { description: "Invalid snapshot" } } } },
    "/v1/account-data/adoption/confirm": { post: { description: "Execute an exact confirmed adoption preview idempotently", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/AdoptionConfirmationRequest" } } } }, responses: { "200": { description: "Adoption executed or replayed idempotently" }, "409": { description: "Preview, resolution, active-session or idempotency conflict" } } } },
    "/v1/account/recovery-codes": { post: { description: "Replace the account's ten one-time recovery codes after recent reauthentication", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/EmptyRequest" } } } }, responses: { "200": { description: "Recovery codes returned once" }, "401": { description: "Recent reauthentication required" } } } },
    "/v1/public/recovery-codes/consume": { post: { security: [], description: "Consume one possession recovery code and issue a Firebase custom token", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/RecoveryCodeConsumeRequest" } } } }, responses: { "200": { description: "Recovery code consumed" }, "401": { description: "Invalid recovery code" }, "409": { description: "Recovery code already used" } } } },
    "/v1/account/session/revoke": { post: { description: "Revoke current and stale Firebase sessions idempotently", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/OperationRequest" } } } }, responses: { "200": { description: "Sessions revoked" }, "503": { description: "Revocation pending; account remains bound" } } } },
    "/v1/account/deletion": { post: { description: "Delete the authenticated account after recent reauthentication and return a verified proof", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/OperationRequest" } } } }, responses: { "200": { description: "Remote deletion and proof complete" }, "401": { description: "Recent reauthentication required" }, "503": { description: "Remote deletion pending" } } } },
    "/v1/public/deletion-proofs/{proofId}": { get: { security: [], description: "Read an opaque server deletion proof", parameters: [{ name: "proofId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Deletion proof" }, "404": { description: "Proof unavailable" } } } },
    "/v1/public/deletion-operations/status": { post: { security: [], description: "Resume an in-app deletion after its Firebase account has been removed, using the operation-bound secret", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/PublicDeletionStatus" } } } }, responses: { "200": { description: "Deletion operation status" }, "404": { description: "Operation unavailable" } } } },
    "/v1/tracks": { get: { responses: { "200": { description: "Account track access" } } } },
    "/v1/content/versions": { get: { responses: { "200": { description: "Current immutable content metadata" } } } },
    "/v1/content/reports": { post: { security: [{ appCheckAuth: [] }], description: "App Check is required. Account and contact linkage are stored only when explicitly requested; account linkage additionally requires an optional Firebase bearer token.", parameters: [{ "$ref": "#/components/parameters/FirebaseAppCheck" }], requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/CreateContentReport" } } } }, responses: { "201": { description: "Content report accepted" }, "200": { description: "Duplicate client submission" }, "400": { description: "Invalid report" }, "401": { description: "Valid App Check required or account linkage authentication required" }, "429": { description: "Anonymous report rate limit exceeded" } } } },
    "/v1/admin/content-reports": { get: { description: "Open, in-review, and resolved content reports for the configured administrator with a verified Firebase email.", responses: { "200": { description: "Content report triage queue" }, "401": { description: "Valid Firebase bearer token required" }, "403": { description: "Verified configured administrator required" } } } },
    "/v1/admin/privacy-requests": { get: { description: "Minimal deadline-ordered privacy request queue for the verified configured administrator", responses: { "200": { description: "Privacy request queue" }, "403": { description: "Administrator required" } } } },
    "/v1/admin/privacy-requests/{requestId}": { get: { description: "Read audited privacy request details", parameters: [{ "$ref": "#/components/parameters/PrivacyRequestId" }], responses: { "200": { description: "Privacy request details" }, "404": { description: "Request unavailable" } } }, patch: { description: "Apply one revision-guarded privacy request lifecycle action", parameters: [{ "$ref": "#/components/parameters/PrivacyRequestId" }], requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/PrivacyRequestAdminAction" } } } }, responses: { "200": { description: "Transition applied" }, "409": { description: "Revision or lifecycle conflict" }, "503": { description: "Response email unavailable" } } } },
    "/v1/admin/legal-requests": { get: { description: "List the minimal consumer-case queue for the verified administrator.", responses: { "200": { description: "Consumer-case queue" }, "403": { description: "Administrator required" } } } },
    "/v1/admin/legal-requests/{requestId}": { get: { description: "Read audited consumer-case details.", responses: { "200": { description: "Consumer-case details" }, "404": { description: "Case unavailable" } } }, patch: { description: "Apply a revision-guarded review, answer, closure, or legal-hold action.", responses: { "200": { description: "Action applied" }, "409": { description: "Revision or lifecycle conflict" }, "503": { description: "Answer delivery unavailable" } } } },
    "/v1/admin/security-incidents": { post: { description: "Create a minimal encrypted security-incident register record; verified configured administrator only.", requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/SecurityIncidentCreate" } } } }, responses: { "201": { description: "Incident created", content: { "application/json": { schema: { "$ref": "#/components/schemas/SecurityIncidentResponse" } } } }, "403": { description: "Administrator required" } } }, get: { description: "List security incidents without sensitive details or recipient data.", responses: { "200": { description: "Incident queue", content: { "application/json": { schema: { "$ref": "#/components/schemas/SecurityIncidentListResponse" } } } }, "403": { description: "Administrator required" } } } },
    "/v1/admin/security-incidents/{incidentId}": { get: { description: "Read audited encrypted incident details.", parameters: [{ "$ref": "#/components/parameters/SecurityIncidentId" }], responses: { "200": { description: "Incident details", content: { "application/json": { schema: { "$ref": "#/components/schemas/SecurityIncidentResponse" } } } }, "404": { description: "Incident unavailable" } } }, patch: { description: "Apply an explicit revision-guarded incident action. UODO submission is recorded manually; this API never sends reports to UODO.", parameters: [{ "$ref": "#/components/parameters/SecurityIncidentId" }], requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/SecurityIncidentAction" } } } }, responses: { "200": { description: "Incident action applied", content: { "application/json": { schema: { "$ref": "#/components/schemas/SecurityIncidentResponse" } } } }, "409": { description: "Revision or legal-lifecycle conflict" }, "503": { description: "Subject-notification email unavailable" } } } },
    "/v1/admin/security-incidents/{incidentId}/authority-exports/{version}": { get: { description: "Read one exact encrypted, versioned UODO export and audit the read.", parameters: [{ "$ref": "#/components/parameters/SecurityIncidentId" }, { name: "version", in: "path", required: true, schema: { type: "integer", minimum: 1 } }], responses: { "200": { description: "Exact prepared export", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["payload", "digest", "version"], properties: { payload: { type: "string", minLength: 1 }, digest: { type: "string", pattern: "^[A-Za-z0-9_-]{43}$" }, version: { type: "integer", minimum: 1 } } } } } }, "404": { description: "Export unavailable" } } } },
    "/v1/admin/overview": { get: { description: "Bounded operational metrics from Firestore and question-bank availability from the configured checksum-verified immutable content release.", responses: { "200": { description: "Published-content, usage, and report statistics" }, "401": { description: "Valid Firebase bearer token required" }, "403": { description: "Verified configured administrator required" } } } },
    "/v1/admin/questions": { get: { description: "Paginated inspection of checksum-verified, locally configured published artifacts. The endpoint never dereferences package URIs.", parameters: [{ name: "trackId", in: "query", required: false, schema: { type: "string" } }, { name: "q", in: "query", required: false, schema: { type: "string", maxLength: 160 } }, { name: "page", in: "query", required: false, schema: { type: "integer", minimum: 1 } }, { name: "pageSize", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 100 } }], responses: { "200": { description: "Question page from verified published artifacts" }, "400": { description: "Invalid query parameters" }, "503": { description: "Question package inspection is not configured" }, "401": { description: "Valid Firebase bearer token required" }, "403": { description: "Verified configured administrator required" } } } },
    "/v1/admin/content-reports/{clientSubmissionId}": { patch: { description: "Advance one report through the server-owned triage state machine; a verified Firebase token for the configured administrator is required.", parameters: [{ name: "clientSubmissionId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { required: true, content: { "application/json": { schema: { "$ref": "#/components/schemas/TransitionContentReport" } } } }, responses: { "200": { description: "Status transition applied or repeated idempotently" }, "400": { description: "Invalid status transition request" }, "401": { description: "Valid Firebase bearer token required" }, "403": { description: "Verified configured administrator required" }, "404": { description: "Report not found" }, "409": { description: "Status transition is not allowed" } } } },
  },
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "Firebase ID token" }, appCheckAuth: { type: "apiKey", in: "header", name: "X-Firebase-AppCheck" } },
    parameters: { FirebaseAppCheck: { name: "X-Firebase-AppCheck", in: "header", required: true, schema: { type: "string", minLength: 1 } }, PrivacyRequestId: { name: "requestId", in: "path", required: true, schema: { type: "string", pattern: "^pr_[0-9a-f-]{36}$" } }, SecurityIncidentId: { name: "incidentId", in: "path", required: true, schema: { type: "string", pattern: "^si_[0-9a-f-]{36}$" } } },
    schemas: {
      SecurityIncidentCreate: { type: "object", additionalProperties: false, required: ["title", "details", "detectedAt", "categories", "dataSubjectCount", "recordCount", "specialData", "confidentialityImpact", "integrityImpact", "availabilityImpact", "consequences", "likelihood", "severity", "containment", "remediation", "prevention", "postmortem"], properties: { title: { type: "string", minLength: 1, maxLength: 200 }, details: { type: "string", minLength: 1, maxLength: 50000 }, detectedAt: { type: "string", format: "date-time" }, occurredAt: { type: "string", format: "date-time" }, containedAt: { type: "string", format: "date-time" }, categories: { type: "string" }, dataSubjectCount: { type: "string" }, recordCount: { type: "string" }, specialData: { type: "boolean" }, confidentialityImpact: { type: "string" }, integrityImpact: { type: "string" }, availabilityImpact: { type: "string" }, consequences: { type: "string" }, likelihood: { type: "string" }, severity: { type: "string" }, containment: { type: "string" }, remediation: { type: "string" }, prevention: { type: "string" }, postmortem: { type: "string" } } },
      SecurityIncidentAction: { oneOf: SECURITY_INCIDENT_ACTION_SCHEMAS },
      SecurityIncidentAssessment: { type: "object", additionalProperties: false, required: ["details", "detectedAt", "categories", "dataSubjectCount", "recordCount", "specialData", "confidentialityImpact", "integrityImpact", "availabilityImpact", "consequences", "likelihood", "severity", "containment", "remediation", "prevention", "postmortem"], properties: { details: { type: "string" }, detectedAt: { type: "string", format: "date-time" }, occurredAt: { type: "string", format: "date-time", nullable: true }, containedAt: { type: "string", format: "date-time", nullable: true }, categories: { type: "string" }, dataSubjectCount: { type: "string" }, recordCount: { type: "string" }, specialData: { type: "boolean" }, confidentialityImpact: { type: "string" }, integrityImpact: { type: "string" }, availabilityImpact: { type: "string" }, consequences: { type: "string" }, likelihood: { type: "string" }, severity: { type: "string" }, containment: { type: "string" }, remediation: { type: "string" }, prevention: { type: "string" }, postmortem: { type: "string" } } },
      SecurityIncidentListItem: { type: "object", additionalProperties: false, required: ["incidentId", "classification", "authorityDecision", "authorityDeliveryStatus", "subjectDecision", "subjectNotificationStatus", "awarenessAt", "authorityDeadlineAt", "closedAt", "revision", "legalHold", "nextAction"], properties: { incidentId: { type: "string" }, classification: { enum: ["triage", "breach_confirmed", "not_a_breach"] }, authorityDecision: { enum: ["undecided", "required", "not_required"] }, authorityDeliveryStatus: { enum: ["not_started", "submitted", "supplemented"] }, subjectDecision: { enum: ["undecided", "required", "not_required"] }, subjectNotificationStatus: { enum: ["not_started", "prepared", "pending", "sent", "failed", "unknown"] }, awarenessAt: { type: "string", nullable: true }, authorityDeadlineAt: { type: "string", nullable: true }, closedAt: { type: "string", nullable: true }, revision: { type: "integer", minimum: 0 }, legalHold: { type: "boolean" }, nextAction: { enum: ["acknowledge_awareness", "classify", "decide_authority", "prepare_authority_export", "record_authority_submission", "decide_subject", "prepare_subject_notification", "resolve_subject_notification_unknown", "send_subject_notification", "close", "none"] } } },
      SecurityIncidentAuditSnapshot: { type: "object", additionalProperties: false, properties: { classification: { enum: ["triage", "breach_confirmed", "not_a_breach"] }, authorityDecision: { enum: ["undecided", "required", "not_required"] }, authorityDeliveryStatus: { enum: ["not_started", "submitted", "supplemented"] }, subjectDecision: { enum: ["undecided", "required", "not_required"] }, subjectNotificationStatus: { enum: ["not_started", "prepared", "pending", "sent", "failed", "unknown"] } } },
      SecurityIncidentAuditEntry: { type: "object", additionalProperties: false, required: ["event", "actorPseudonym", "at", "revision", "assessmentVersion", "snapshot"], properties: { event: { type: "string" }, actorPseudonym: { type: "string" }, at: { type: "string" }, revision: { type: "integer", nullable: true }, assessmentVersion: { type: "integer", nullable: true }, snapshot: { allOf: [{ "$ref": "#/components/schemas/SecurityIncidentAuditSnapshot" }], nullable: true } } },
      SecurityIncidentPreparedRecipient: { type: "object", additionalProperties: false, required: ["recipientPseudonym", "snapshotVersion"], properties: { recipientPseudonym: { type: "string" }, snapshotVersion: { type: "integer", minimum: 1 } } },
      SecurityIncidentDelivery: { type: "object", additionalProperties: false, required: ["recipientPseudonym", "snapshotVersion", "status", "deliveryId"], properties: { recipientPseudonym: { type: "string" }, snapshotVersion: { type: "integer", minimum: 1 }, status: { enum: ["pending", "sent", "failed", "unknown", "superseded"] }, deliveryId: { type: "string", format: "uuid" } } },
      SecurityIncidentDetails: { allOf: [{ "$ref": "#/components/schemas/SecurityIncidentListItem" }, { type: "object", additionalProperties: false, required: ["title", "details", "assessment", "createdAt", "updatedAt", "authorityExportVersion", "assessmentVersion", "authorityReason", "subjectReason", "authoritySubmissionReference", "preparedRecipients", "auditHistory", "subjectNotifications"], properties: { title: { type: "string" }, details: { type: "string" }, assessment: { "$ref": "#/components/schemas/SecurityIncidentAssessment" }, createdAt: { type: "string" }, updatedAt: { type: "string" }, authorityExportVersion: { type: "integer", nullable: true }, assessmentVersion: { type: "integer", minimum: 1 }, authorityReason: { type: "string", nullable: true }, subjectReason: { type: "string", nullable: true }, authoritySubmissionReference: { type: "string", nullable: true }, preparedRecipients: { type: "array", items: { "$ref": "#/components/schemas/SecurityIncidentPreparedRecipient" } }, auditHistory: { type: "array", items: { "$ref": "#/components/schemas/SecurityIncidentAuditEntry" } }, subjectNotifications: { type: "array", items: { "$ref": "#/components/schemas/SecurityIncidentDelivery" } } } }] },
      SecurityIncidentResponse: { type: "object", additionalProperties: false, required: ["incident"], properties: { incident: { "$ref": "#/components/schemas/SecurityIncidentDetails" } } },
      SecurityIncidentListResponse: { type: "object", additionalProperties: false, required: ["incidents"], properties: { incidents: { type: "array", items: { "$ref": "#/components/schemas/SecurityIncidentListItem" } } } },
      ProgressMutation: {
        type: "object",
        required: ["mutationId", "kind", "recordType", "trackId", "targetId", "expectedVersion", "fingerprint", "state"],
        properties: {
          mutationId: { type: "string", minLength: 16, maxLength: 128 },
          kind: { type: "string", enum: ["node", "item"] },
          recordType: { type: "string", enum: ["active_track", "training_session_summary", "training_session_result", "training_attempt", "review_queue_entry"] },
          trackId: { type: "string" },
          targetId: { type: "string" },
          expectedVersion: { anyOf: [{ type: "integer", minimum: 0 }, { type: "null" }] },
          fingerprint: { type: "string", pattern: "^[a-f0-9]{64}$" },
          state: { type: "object", additionalProperties: true },
        },
      },
      SyncRequest: {
        type: "object",
        required: ["expectedAccountRevision", "mutations"],
        properties: {
          expectedAccountRevision: { type: "integer", minimum: 0 },
          deviceId: { anyOf: [{ type: "string", format: "uuid" }, { type: "null" }] },
          mutations: { type: "array", minItems: 1, maxItems: 100, items: { "$ref": "#/components/schemas/ProgressMutation" } },
        },
      },
      GuestMergeSnapshot: {
        type: "object",
        additionalProperties: false,
        required: ["guestSnapshotVersion", "guestUserId", "records", "activeSession", "pendingJournal"],
        properties: {
          guestSnapshotVersion: { type: "integer", minimum: 0 },
          guestUserId: { type: "string", format: "uuid" },
          records: { type: "array", maxItems: 1000, items: { "$ref": "#/components/schemas/GuestMergeRecord" } },
          activeSession: { type: "boolean" },
          pendingJournal: { type: "boolean" },
        },
      },
      GuestMergeRecord: {
        type: "object",
        additionalProperties: false,
        required: ["fingerprint", "recordId", "recordType", "state", "trackId", "version"],
        properties: {
          fingerprint: { type: "string", pattern: "^[a-f0-9]{64}$" },
          recordId: { type: "string" },
          recordType: { type: "string", enum: ["active_track", "training_session_summary", "training_session_result", "training_attempt", "review_queue_entry"] },
          state: { type: "object", additionalProperties: true },
          trackId: { type: "string" },
          version: { type: "integer", minimum: 0 },
        },
      },
      AdoptionConfirmationRequest: {
        type: "object",
        additionalProperties: false,
        required: ["deviceId", "snapshot", "confirmation"],
        properties: {
          deviceId: { type: "string", format: "uuid" },
          snapshot: { "$ref": "#/components/schemas/GuestMergeSnapshot" },
          confirmation: {
            type: "object",
            additionalProperties: false,
            required: ["operationId", "previewFingerprint", "protocolVersion", "resolutions"],
            properties: {
              operationId: { type: "string", format: "uuid" },
              previewFingerprint: { type: "string", pattern: "^[a-f0-9]{64}$" },
              protocolVersion: { type: "integer", enum: [1] },
              resolutions: { type: "array", maxItems: 1000, items: { type: "object", additionalProperties: false, required: ["conflictId", "resolution"], properties: { conflictId: { type: "string" }, resolution: { type: "string", enum: ["keep_guest", "keep_account", "manual_required"] } } } },
            },
          },
        },
      },
      EmptyRequest: { type: "object", additionalProperties: false },
      OperationRequest: { type: "object", additionalProperties: false, required: ["operationId"], properties: { operationId: { type: "string", format: "uuid" } } },
      RecoveryCodeConsumeRequest: { type: "object", additionalProperties: false, required: ["code"], properties: { code: { type: "string", pattern: "^[A-Z2-9]{4}(?:-[A-Z2-9]{4}){3}$" } } },
      CreateAccountPrivacyRequest: { type: "object", additionalProperties: false, required: ["right"], properties: { right: { "$ref": "#/components/schemas/PrivacyRight" }, narrative: { type: "string", minLength: 1, maxLength: 2000 } } },
      CreatePublicPrivacyRequest: { type: "object", additionalProperties: false, required: ["email", "right"], properties: { email: { type: "string", format: "email", maxLength: 320 }, right: { "$ref": "#/components/schemas/PrivacyRight" }, narrative: { type: "string", minLength: 1, maxLength: 2000 }, reportSubmissionIds: { type: "array", maxItems: 10, items: { type: "string", format: "uuid" } } } },
      PrivacyRight: { type: "string", enum: ["access", "rectification", "erasure", "restriction", "objection", "portability", "consent_withdrawal"] },
      PrivacyTokenExchange: { type: "object", additionalProperties: false, required: ["token"], properties: { token: { type: "string", minLength: 32, maxLength: 512 } } },
      PublicPrivacySession: { type: "object", additionalProperties: false, required: ["sessionToken"], properties: { sessionToken: { type: "string", minLength: 32, maxLength: 512 } } },
      PublicDeletionStatus: { type: "object", additionalProperties: false, required: ["operationId", "operationSecret"], properties: { operationId: { type: "string", format: "uuid" }, operationSecret: { type: "string", pattern: "^[a-f0-9]{64}$" } } },
      PrivacyRequestAdminAction: { oneOf: [
        { type: "object", additionalProperties: false, required: ["action", "reason", "expectedRevision"], properties: { action: { const: "require_verification" }, reason: { type: "string", minLength: 1, maxLength: 2000 }, expectedRevision: { type: "integer", minimum: 0 } } },
        { type: "object", additionalProperties: false, required: ["action", "reason", "expectedRevision"], properties: { action: { const: "verify_subject" }, reason: { type: "string", minLength: 1, maxLength: 2000 }, expectedRevision: { type: "integer", minimum: 0 } } },
        { type: "object", additionalProperties: false, required: ["action", "expectedRevision"], properties: { action: { const: "start_review" }, expectedRevision: { type: "integer", minimum: 0 } } },
        { type: "object", additionalProperties: false, required: ["action", "expectedRevision"], properties: { action: { const: "execute_export" }, expectedRevision: { type: "integer", minimum: 0 } } },
        { type: "object", additionalProperties: false, required: ["action", "reason", "noticeLocale", "expectedRevision"], properties: { action: { const: "extend" }, reason: { type: "string", minLength: 1, maxLength: 2000 }, noticeLocale: { type: "string", enum: ["pl", "en"] }, expectedRevision: { type: "integer", minimum: 0 } } },
        { type: "object", additionalProperties: false, required: ["action", "expectedRevision"], properties: { action: { const: "retry_extension_notice" }, expectedRevision: { type: "integer", minimum: 0 } } },
        { type: "object", additionalProperties: false, required: ["action", "outcome", "response", "reason", "complaintInformationIncluded", "executionEvidence", "expectedRevision"], properties: { action: { const: "prepare_response" }, outcome: { type: "string", enum: ["fulfilled", "partially_fulfilled", "refused"] }, response: { type: "string", minLength: 1, maxLength: 250000 }, reason: { type: "string", minLength: 1, maxLength: 2000 }, complaintInformationIncluded: { const: true }, executionEvidence: { type: "string", minLength: 1, maxLength: 512 }, expectedRevision: { type: "integer", minimum: 0 } } },
        { type: "object", additionalProperties: false, required: ["action", "expectedRevision"], properties: { action: { type: "string", enum: ["deliver", "close"] }, expectedRevision: { type: "integer", minimum: 0 } } },
      ] },
      AccountDataExport: {
        type: "object",
        additionalProperties: false,
        required: ["schemaVersion", "exportId", "exportedAt", "scope", "article15Information", "portable", "accountContext", "manifest"],
        properties: {
          schemaVersion: { type: "string", const: "account-data-export-v1" },
          exportId: { type: "string", pattern: "^export_[A-Za-z0-9_-]{32}$" },
          exportedAt: { type: "string", format: "date-time" },
          scope: { type: "object", additionalProperties: false, required: ["portable", "accountContext"], properties: { portable: { type: "string", const: "user_data_and_activity" }, accountContext: { type: "string", const: "user_visible_account_context" } } },
          article15Information: { type: "object", additionalProperties: false, required: ["purposes", "dataCategories", "recipientCategories", "retentionCriteria", "dataSources", "internationalTransfers", "automatedDecisionMaking", "rightsAndComplaint"], properties: { purposes: { type: "array", items: { type: "string" } }, dataCategories: { type: "array", items: { type: "string" } }, recipientCategories: { type: "array", items: { type: "string" } }, retentionCriteria: { type: "array", items: { type: "string" } }, dataSources: { type: "array", items: { type: "string" } }, internationalTransfers: { type: "string" }, automatedDecisionMaking: { type: "string" }, rightsAndComplaint: { type: "string" } } },
          portable: {
            type: "object",
            additionalProperties: false,
            required: ["profile", "progress", "linkedContentReports"],
            properties: {
              profile: { type: "object", additionalProperties: false, required: ["createdAt", "identity"], properties: { createdAt: { type: "string", format: "date-time" }, identity: { type: "object", additionalProperties: false, required: ["provider", "email", "emailVerified"], properties: { provider: { type: "string" }, email: { anyOf: [{ type: "string", format: "email" }, { type: "null" }] }, emailVerified: { type: "boolean" } } } } },
              progress: { type: "array", items: { "$ref": "#/components/schemas/AccountDataExportProgress" } },
              linkedContentReports: { type: "array", items: { "$ref": "#/components/schemas/AccountDataExportContentReport" } },
            },
          },
          accountContext: {
            type: "object",
            additionalProperties: false,
            required: ["trackAccess", "entitlements", "devices", "syncMetadata", "exportHistory"],
            properties: {
              trackAccess: { type: "array", items: { type: "object", additionalProperties: true } },
              entitlements: { type: "array", items: { type: "object", additionalProperties: true } },
              devices: { type: "array", items: { type: "object", additionalProperties: true } },
              syncMetadata: { type: "object", additionalProperties: true },
              exportHistory: { type: "array", items: { type: "object", additionalProperties: true } },
            },
          },
          manifest: { type: "object", additionalProperties: false, required: ["included", "omitted"], properties: { included: { type: "array", items: { type: "string" } }, omitted: { type: "array", items: { type: "object", additionalProperties: false, required: ["category", "reason"], properties: { category: { type: "string" }, reason: { type: "string" } } } } } },
        },
      },
      AccountDataExportProgress: { type: "object", additionalProperties: false, required: ["kind", "recordType", "trackId", "targetId", "version", "fingerprint", "state", "lastMutationId", "updatedAt"], properties: { kind: { type: "string", enum: ["node", "item"] }, recordType: { type: "string" }, trackId: { type: "string" }, targetId: { type: "string" }, version: { type: "integer", minimum: 0 }, fingerprint: { type: "string" }, state: { type: "object", additionalProperties: true }, lastMutationId: { type: "string" }, updatedAt: { type: "string", format: "date-time" } } },
      AccountDataExportContentReport: { type: "object", additionalProperties: false, required: ["id", "clientSubmissionId", "trackId", "contentVersion", "itemId", "reason", "description", "context", "linkage", "status", "createdAt", "updatedAt"], properties: { id: { type: "string" }, clientSubmissionId: { type: "string" }, trackId: { type: "string" }, contentVersion: { type: "string" }, itemId: { type: "string" }, reason: { type: "string" }, description: { type: "string" }, context: { type: "object", additionalProperties: true }, linkage: { type: "string", enum: ["account", "account_and_contact"] }, status: { type: "string" }, createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" } } },
      CreateContentReport: {
        type: "object",
        required: ["clientSubmissionId", "trackId", "contentVersion", "itemId", "reason", "description"],
        properties: {
          clientSubmissionId: { type: "string", format: "uuid" },
          trackId: { type: "string" },
          contentVersion: { type: "string" },
          itemId: { type: "string" },
          reason: { type: "string", enum: ["incorrect_answer", "unclear_explanation", "outdated_content", "technical_issue", "other"] },
          description: { type: "string", maxLength: 280, description: "Optional note. Blank input is stored as a neutral fixed description; obvious contact data, URLs, passwords and codes are rejected." },
          context: { "$ref": "#/components/schemas/ContentReportContext" },
          linkAccount: { type: "boolean", default: false, description: "Explicit opt-in to attach the authenticated Patternly account identifier." },
          contactEmail: { type: "string", format: "email", description: "Explicit opt-in contact address; never inferred from authentication." },
        },
      },
      ContentReportContext: {
        type: "object",
        additionalProperties: false,
        required: ["releasePackageId", "trackNode", "modeRoute", "locale", "appBuild", "platform", "occurredAt"],
        properties: {
          releasePackageId: { type: "string", minLength: 1, maxLength: 256 },
          trackNode: { anyOf: [{ type: "string", minLength: 1, maxLength: 128 }, { type: "null" }] },
          modeRoute: { type: "string", enum: ["practice_feedback_details", "answer_review"] },
          locale: { type: "string", enum: ["en", "pl"] },
          appBuild: { type: "string", minLength: 1, maxLength: 32 },
          platform: { type: "string", enum: ["ios", "android"] },
          occurredAt: { type: "string", format: "date-time" },
        },
      },
      TransitionContentReport: {
        type: "object",
        additionalProperties: false,
        required: ["status"],
        properties: { status: { type: "string", enum: ["open", "in_review", "resolved", "closed"] } },
      },
    },
  },
});

export type OpenApiDocument = typeof OPENAPI_DOCUMENT;
